name: Version bump and release

on:
  push:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Damit GitHub Actions pushen darf

    steps:
      # 1. Checkout repository mit Token
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true  # Wichtig, damit git push funktioniert

      # 2. Install xmlstarlet
      - name: Install xmlstarlet
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet

      # 3. Patch-Version hochzählen
      - name: Bump version
        id: version
        run: |
          CURRENT=$(xmlstarlet sel -t -v "//info/version" mod.manifest || echo "0.0.0")
          echo "Current version: $CURRENT"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
          PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION"

          xmlstarlet ed -L -u "//info/version" -v "$NEW_VERSION" mod.manifest

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      # 4. Commit und push
      - name: Commit and push version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add mod.manifest
          git commit -m "chore: bump version to ${{ steps.version.outputs.new_version }}" || echo "No changes to commit"

          git tag "${{ steps.version.outputs.new_version }}" || echo "Tag exists"
          git push origin main --tags

      # 5. Optional: Release auf GitHub erstellen
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.new_version }}
          name: Release ${{ steps.version.outputs.new_version }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
