name: Version bump test

on:
  push:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Erlaubt Push auf das Repo

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      # 2. Bump version in mod.manifest
      - name: Bump version
        id: version
        run: |
          CURRENT=$(xmlstarlet sel -t -v "//info/version" mod.manifest || echo "0.0.0")
          echo "Current version: $CURRENT"

          # Patch-Version hochzählen
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
          PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION"
          xmlstarlet ed -L -u "//info/version" -v "$NEW_VERSION" mod.manifest

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      # 3. Commit & push
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add mod.manifest
          git commit -m "chore: bump version to ${{ steps.version.outputs.new_version }}" || echo "No changes to commit"

          git tag "${{ steps.version.outputs.new_version }}" || echo "Tag exists"
          git push origin main --tags
